### ISSUE TITLE
Ошибка в переводе

### ISSUE THREAD

**Issue by vasil-1603** [dotnet/dotnet-api-docs.ru-ru#1]
Serialize all appearance properties, such as color or line style, if they have non-default values.
Неправильный перевод:
Сериализуются все свойства внешнего вида, такие как цвет или стиль линии, если у них **не имеется** значений, отличных от значений по умолчанию.
Правильный перевод:
Сериализуются все свойства внешнего вида, такие как цвет или стиль линии, если у них **имеется** значение, отличное от значений по умолчанию.
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 5a67fbd4-dd9a-2be1-1bd9-fdfad8cbcef3
* Version Independent ID: a4affade-61e3-de83-c8e3-e02415011215
* Content: [SerializationContents Enum (System.Windows.Forms.DataVisualization.Charting)](https://docs.microsoft.com/ru-ru/dotnet/api/system.windows.forms.datavisualization.charting.serializationcontents?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms.DataVisualization.Charting/SerializationContents.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.Windows.Forms.DataVisualization.Charting/SerializationContents.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Здравствуйте, @vasil-1603  ! 

 Спасибо за отзыв. 

 Мы активно просматриваем комментарии и скоро ответим Вам. 

 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Здравствуйте, @vasil-1603  !  
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/dotnet/api/system.windows.forms.datavisualization.charting.serializationcontents?view=netframework-4.7.2.  
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
