### ISSUE TITLE
EventWaitHandle.OpenExisting method for .net core

### ISSUE THREAD

**Issue by 23Alex24** [dotnet/dotnet-api-docs.ru-ru#2]
On documentation for EventWaitHandle.OpenExisting method example is shown with EventWaitHandleRights. But on .net standard and .net core no overloads for constructor EventWaitHandle with EventWaitHandleRights and no methods GetAccessControl  / SetAccessControl.
Thus the example is not correct.

[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 35bfc5d9-ec45-165a-52e6-b676df32b25e
* Version Independent ID: c30273ca-0606-2d14-44ad-c7eb884c2459
* Content: [EventWaitHandle.OpenExisting Method (System.Threading)](https://docs.microsoft.com/ru-ru/dotnet/api/system.threading.eventwaithandle.openexisting?view=netcore-2.1)
* Content Source: [xml/System.Threading/EventWaitHandle.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.Threading/EventWaitHandle.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by 23Alex24** [comment]
Can block. Issue for en-us culture https://github.com/dotnet/docs/issues/9149

**Comment by 23Alex24** [comment]
The TryOpenExisting method also has a mention about EventWaitHandleRights

**Comment by CeciAc** [comment]
Hello, @<contributor's GITHUB name>,

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/dotnet/docs/issues/9149. For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team

**Comment by 23Alex24** [comment]
Ok. Thanks
