### ISSUE TITLE
The key word "Volatile"

### ISSUE THREAD

**Issue by KirillSL** [dotnet/dotnet-api-docs.ru-ru#22]
Dear collegues.
The compiled code on the Intel Core i5-3230M, .NET Framework 4.6.1 in release x86 for Thread.VolatileRead and Thread.VolatileWrite has next results.

VolatileRead
CPU Disasm
Address   Hex dump          Command                                  Comments
6BD1E1B5  |.  8B01          MOV EAX,DWORD PTR DS:[ECX]
6BD1E1B7  |.  F0:830C24 00  LOCK OR DWORD PTR SS:[ESP],00000000

VolatileWrite
CPU Disasm
Address   Hex dump          Command                                  Comments
6BD1E1C5  |.  F0:830C24 00  LOCK OR DWORD PTR SS:[ESP],00000000
6BD1E1CA  |.  8911          MOV DWORD PTR DS:[ECX],EDX

But the compiled code for a field with key word volatile has next results

read from field with key word volatile
CPU Disasm
Address   Hex dump          Command                                  Comments
017804ED    A1 08442F01     MOV EAX,DWORD PTR DS:[12F4408]

write from field with key word volatile
CPU Disasm
Address   Hex dump          Command                                  Comments
017804F5    C705 08442F01 0 MOV DWORD PTR DS:[12F4408],8

I think that according to 8.2.3.5 Intra-Processor Forwarding Is Allowed of "Intel® 64 and IA-32 Architectures Developer's Manual" Thread.VolatileWrite is stronger then the key word volatile.
If my opinion is not true, then please explain why?

P.S. Please, dublicate answer to email address 6006299@gmail.com.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 3fbe2942-220b-5a42-4ede-1d7fa53a8ec7
* Version Independent ID: 4fe75771-17cb-829b-a553-5ca3696cedb3
* Content: [Thread.VolatileWrite Method (System.Threading)](https://docs.microsoft.com/ru-ru/dotnet/api/system.threading.thread.volatilewrite?view=netframework-4.6.1)
* Content Source: [xml/System.Threading/Thread.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.Threading/Thread.xml)
* Product: **dotnet-api**
* Technology: **system.threading**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @KirillSL 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by MSDN-WhiteKnight** [comment]
Could it be that the compiler generated instruction without lock in second case due to optimization? If it was obvious that the field is accessed only from a single thread in the program, it might choose to optimize it out and generate regular read instruction instead; while Thread.VolatileRead does not have this possibility.

**Comment by KirillSL** [comment]
- This article contains note: "In C#, using the volatile modifier on a field guarantees that all access to that field uses VolatileRead or VolatileWrite". VolatileWrite has link to https://docs.microsoft.com/ru-ru/dotnet/api/system.threading.thread.volatilewrite?view=netframework-4.6.1 
- You can take source code from https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/volatile and investigate compiled code.

**Comment by MSDN-WhiteKnight** [comment]
Actually you are right. The information in this article is contradicting https://docs.microsoft.com/en-us/dotnet/api/system.threading.volatile?redirectedfrom=MSDN&view=netframework-4.8 that states 

>In C#, using the volatile modifier on a field guarantees that every access to that field uses the Volatile.Read and Volatile.Write methods... 

Looks like `volatile` keyword was using `Thread.VolatileRead` in older .NET versions and later it was changed to [Volatile.Read](https://docs.microsoft.com/en-us/dotnet/api/system.threading.volatile.read?view=netframework-4.8#System_Threading_Volatile_Read_System_Int32__), but this article was not updated to reflect that. Would you re-submit this issue to [dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs/issues) repository, where source article issues are tracked, with a link to this discussion?

**Comment by mikedn** [comment]
> In C#, using the volatile modifier on a field guarantees that every access to that field uses the Volatile.Read and Volatile.Write methods...

That piece of documentation is wrong. C#'s `volatile` results in field access IL instructions using the [volatile.](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.volatile?view=netcore-2.2) prefix. It has nothing to do with `Volatile.Read/Write`, except that those try to mimic `volatile`.

**Comment by MSDN-WhiteKnight** [comment]
True. That's even more confusing. So the correct picture should be as follows:

- Accessing field with `volatile` keyword: directly generates field access instruction with `volatile.` prefix

- `Volatile.Read/Write`: same as above, but via a method call

- `Thread.VolatileRead/VolatileWrite`: performs read/write with full memory barrier (`Thread.MemoryBarrier()` call - see https://referencesource.microsoft.com/#mscorlib/system/threading/thread.cs,1599)

So KirillSL is right in that `Thread.VolatileRead/VolatileWrite` is indeed "stronger" then `volatile` keyword. The question is how this should be reflected in documentation. Half of these are just implementation details anyway.

**Comment by mikedn** [comment]
> The question is how this should be reflected in documentation. Half of these are just implementation details anyway.

At the very least the mention regarding the C# `volatile` keyword should be removed from this documentation. And I don't think it would hurt specifying exactly what these method do - things like half/full barrier aren't implementation details IMO.
