### ISSUE TITLE
ext method Append

### ISSUE THREAD

**Issue by x13xxxswatxxx** [dotnet/dotnet-api-docs.ru-ru#24]
Append&lt;TSource&gt;(IEnumerable&lt;TSource&gt;, TSource)	=  adds value to end of sequence

On practice received an exception that there is no such value after the addition.
value is added and returns a new  Dictionary, one in which it is present

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8f6939a0-b36f-4d22-4909-f80732c65500
* Version Independent ID: d5c36c4c-fa2b-87fc-e9de-4ff117f2ff95
* Content: [Dictionary&lt;TKey,TValue&gt;.KeyCollection Class (System.Collections.Generic)](https://docs.microsoft.com/ru-ru/dotnet/api/system.collections.generic.dictionary-2.keycollection?view=netframework-4.8)
* Content Source: [xml/System.Collections.Generic/Dictionary`2+KeyCollection.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.Collections.Generic/Dictionary`2+KeyCollection.xml)
* Product: **dotnet-api**
* Technology: **system.collections**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @x13xxxswatxxx 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
