### ISSUE TITLE
Свойство ProcessName

### ISSUE THREAD

**Issue by vst377** [dotnet/dotnet-api-docs.ru-ru#29]
В комментариях указано "ProcessName Свойство содержит имя исполняемого файла". Это не совсем так. ProcessName содержит название сборки исполняемого файла, имя которого может не совпадать с именем сборки.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 530bea95-e694-38e5-76d1-9b2a902f19cf
* Version Independent ID: 15936e84-bf0b-7e62-86aa-30a2c1d3489a
* Content: [Process.ProcessName Property (System.Diagnostics)](https://docs.microsoft.com/ru-ru/dotnet/api/system.diagnostics.process.processname?view=netframework-4.8)
* Content Source: [xml/System.Diagnostics/Process.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.Diagnostics/Process.xml)
* Product: **dotnet-api**
* Technology: **system.diagnostics**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @vst377
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #3162](https://github.com/dotnet/dotnet-api-docs/issues/3162) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Здравствуйте, @vst377 
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/dotnet/dotnet-api-docs/issues/3162
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
