### ISSUE TITLE
Improve translation of "Returns" in .NET API Browser

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [dotnet/dotnet-api-docs.ru-ru#30]
In .NET API Browser, "Returns" translation in method signature (for example, https://docs.microsoft.com/ru-ru/dotnet/api/system.object.gettype#--------) should be changed from "Возвраты" to "Возвращаемое значение". This is more correct because methods in .NET only return a single value.

**Comment by srvbpigh** [comment]
Hello, @MSDN-WhiteKnight
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @MSDN-WhiteKnight 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/dotnet/api/system.object.gettype#--------

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
