### ISSUE TITLE
интернет эксплорер 11 скачать бесплатно русская версия для windows 7 sp1

### ISSUE THREAD

**Issue by voronaivan93** [dotnet/dotnet-api-docs.ru-ru#5]
Hello . Устранение неполадок неудачной установки Internet Explorer 11..все это установилась где возникли неполадки установки

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: cf4e724a-d8fb-d19b-fae1-e9f1a8809d1f
* Version Independent ID: 18a6d542-c735-f66f-5c34-6a95fc16d1f7
* Content: [AttributeUsageAttribute.Inherited Property (System)](https://docs.microsoft.com/ru-ru/dotnet/api/system.attributeusageattribute.inherited?view=netframework-4.7.2)
* Content Source: [xml/System/AttributeUsageAttribute.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System/AttributeUsageAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Здравствуйте, @voronaivan93 ! 
Благодарим Вас за участие. Наши специалисты могут отвечать только на отзывы по документации. 
Чтобы оставить отзыв по продукту, воспользуйтесь кнопкой «Оставить отзыв о продукте» внизу страницы портала документации. 
А по текущему каналу Вы можете оставлять любые отзывы, связанные с документацией. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
