### ISSUE TITLE
Устранение неполадок неудачной установки Internet Explorer 11    

### ISSUE THREAD

**Issue by voronaivan93** [dotnet/dotnet-api-docs.ru-ru#6]
Устранение неполадок неудачной установки Internet Explorer 11

**Comment by voronaivan93** [comment]
Устранение неполадок неудачной установки Internet Explorer 11

**Comment by LisandroSu** [comment]
Здравствуйте, @voronaivan93 ! 
Благодарим Вас за участие. Наши специалисты могут отвечать только на отзывы по документации. 
Чтобы оставить отзыв по продукту, воспользуйтесь кнопкой «Оставить отзыв о продукте» внизу страницы портала документации. 
А по текущему каналу Вы можете оставлять любые отзывы, связанные с документацией. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
